"""user table

Revision ID: 1b0df21acee9
Revises: 
Create Date: 2022-11-15 22:15:06.356776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b0df21acee9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('gid', sa.Integer(), nullable=False),
    sa.Column('addr_str', sa.String(), nullable=True),
    sa.Column('addr_unit', sa.String(length=64), nullable=True),
    sa.Column('invite_to_rehersal_dinner', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('gid')
    )
    op.create_table('group_resp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gid', sa.Integer(), nullable=True),
    sa.Column('addr_city', sa.String(length=64), nullable=True),
    sa.Column('addr_state', sa.String(length=20), nullable=True),
    sa.Column('addr_zip', sa.String(length=10), nullable=True),
    sa.Column('addr_country', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['gid'], ['group.gid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=10), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('has_plus_one', sa.Boolean(), nullable=True),
    sa.Column('customized_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.gid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('group_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gid', sa.Integer(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gid'], ['group.gid'], ),
    sa.ForeignKeyConstraint(['uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_resp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_submitted', sa.DateTime(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('rsvp_wedding', sa.Boolean(), nullable=True),
    sa.Column('rsvp_rehersal', sa.Boolean(), nullable=True),
    sa.Column('covid_ack', sa.Boolean(), nullable=True),
    sa.Column('dietary_restricions', sa.String(), nullable=True),
    sa.Column('cell', sa.String(length=12), nullable=True),
    sa.Column('general_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_resp')
    op.drop_table('group_links')
    op.drop_table('user')
    op.drop_table('group_resp')
    op.drop_table('group')
    # ### end Alembic commands ###
