"""delete group links

Revision ID: 206258ab306f
Revises: 1b0df21acee9
Create Date: 2022-11-15 22:20:56.547382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '206258ab306f'
down_revision = '1b0df21acee9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_links')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_links',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('gid', sa.INTEGER(), nullable=True),
    sa.Column('uid', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['gid'], ['group.gid'], ),
    sa.ForeignKeyConstraint(['uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
